type PersonalInformation = {
  p_surname: string;
  p_first_name: string;
  p_middle_name: string;
  p_name_extension: string;
  p_birth_date: string;
  p_birth_place: string;
  p_sex_male: string;
  p_sex_female: string;
  p_civil_single: string;
  p_civil_widowed: string;
  p_civil_married: string;
  p_civil_separated: string;
  p_civil_other: string;
  p_weight: string;
  p_height: string;
  p_blood_type: string;
  p_gsis_no: string;
  p_pagibig_no: string;
  p_philhealth_no: string;
  p_sss_no: string;
  p_tin_no: string;
  p_agency_no: string;
  p_citizen_filipino: string;
  p_citizen_dual: string;
  p_citizen_by_birth: string;
  p_citizen_by_naturalization: string;
  p_ra_house: string;
  p_ra_street: string;
  p_ra_subdivision: string;
  p_ra_barangay: string;
  p_ra_city: string;
  p_ra_province: string;
  p_ra_zip: string;
  p_pa_house: string;
  p_pa_street: string;
  p_pa_subdivision: string;
  p_pa_barangay: string;
  p_pa_city: string;
  p_pa_province: string;
  p_pa_zip: string;
  p_telephone: string;
  p_mobile: string;
  p_email: string;
};

type FamilyBackground = {
  fb_spouse_surname: string;
  fb_spouse_first_name: string;
  fb_spouse_middle_name: string;
  fb_spouse_name_extension: string;
  fb_spouse_occupation: string;
  fb_spouse_employer: string;
  fb_spouse_business: string;
  fb_spouse_telephone: string;
  fb_father_surname: string;
  fb_father_first_name: string;
  fb_father_middle_name: string;
  fb_father_name_extension: string;
  fb_mother_maiden_name: string;
  fb_mother_surname: string;
  fb_mother_first_name: string;
  fb_mother_middle_name: string;
  fb_children_name_1: string;
  fb_children_birth_date_1: string;
  fb_children_name_2: string;
  fb_children_birth_date_2: string;
  fb_children_name_3: string;
  fb_children_birth_date_3: string;
  fb_children_name_4: string;
  fb_children_birth_date_4: string;
  fb_children_name_5: string;
  fb_children_birth_date_5: string;
  fb_children_name_6: string;
  fb_children_birth_date_6: string;
  fb_children_name_7: string;
  fb_children_birth_date_7: string;
  fb_children_name_8: string;
  fb_children_birth_date_8: string;
  fb_children_name_9: string;
  fb_children_birth_date_9: string;
  fb_children_name_10: string;
  fb_children_birth_date_10: string;
  fb_children_name_11: string;
  fb_children_birth_date_11: string;
  fb_children_name_12: string;
  fb_children_birth_date_12: string;
};

type EducationBackground = {
  eb_e_school_name: string;
  eb_e_basic_education: string;
  eb_e_period_from: string;
  eb_e_period_to: string;
  eb_e_units_earned: string;
  eb_e_year_graduated: string;
  eb_e_honor_received: string;
  eb_s_school_name: string;
  eb_s_basic_education: string;
  eb_s_period_from: string;
  eb_s_period_to: string;
  eb_s_units_earned: string;
  eb_s_year_graduated: string;
  eb_s_honor_received: string;
  eb_v_school_name: string;
  eb_v_basic_education: string;
  eb_v_period_from: string;
  eb_v_period_to: string;
  eb_v_units_earned: string;
  eb_v_year_graduated: string;
  eb_v_honor_received: string;
  eb_c_school_name: string;
  eb_c_basic_education: string;
  eb_c_period_from: string;
  eb_c_period_to: string;
  eb_c_units_earned: string;
  eb_c_year_graduated: string;
  eb_c_honor_received: string;
  eb_gs_school_name: string;
  eb_gs_basic_education: string;
  eb_gs_period_from: string;
  eb_gs_period_to: string;
  eb_gs_units_earned: string;
  eb_gs_year_graduated: string;
  eb_gs_honor_received: string;
  eb_date: string;
};

type CivilServiceEligibility = Array<{
  cse: string;
  cse_rating: string;
  cse_exam_date: string;
  cse_exam_place: string;
  cse_license_number: string;
  cse_validity_date: string;
}>;

type WorkExperience = Array<{
  w_from: string;
  w_to: string;
  w_position: string;
  w_department: string;
  w_salary: number;
  w_pay_grade: string;
  w_soa: string;
  w_gov_service: string;
}>;

type VoluntaryWork = Array<{
  vw_organization: string;
  vw_from: string;
  vw_to: string;
  vw_hours: number;
  vw_position: string;
}>;

type LearningDevelopment = Array<{
  ld_learning: string;
  ld_from: string;
  ld_to: string;
  ld_hours: string;
  ld_type: string;
  ld_conducted: string;
}>;

type OtherInformation = {
  w_date: string;
  skills: Array<{
    of_skill: string;
    of_recognition: string;
    of_membership: string;
  }>;
  of_date: string;
  of_third_degree_yes: string;
  of_third_degree_no: string;
  of_fourth_degree_yes: string;
  of_fourth_degree_no: string;
  of_affinity_details: string;
  of_guilty_yes: string;
  of_guilty_no: string;
  of_guilty_details: string;
  of_criminal_yes: string;
  of_criminal_no: string;
  of_criminal_date_filled: string;
  of_criminal_status: string;
  of_convicted_yes: string;
  of_convicted_no: string;
  of_convicted_details: string;
  of_resignation_yes: string;
  of_resignation_no: string;
  of_resignation_details: string;
  of_candidate_yes: string;
  of_candidate_no: string;
  of_candidate_details: string;
  of_government_yes: string;
  of_government_no: string;
  of_government_details: string;
  of_immigrant_yes: string;
  of_immigrant_no: string;
  of_immigrant_details: string;
  of_indigenous_yes: string;
  of_indigenous_no: string;
  of_indigenous_details: string;
  of_disability_yes: string;
  of_disability_no: string;
  of_disability_details: string;
  of_solo_parent_yes: string;
  of_solo_parent_no: string;
  of_solo_parent_details: string;
  of_reference_name_1: string;
  of_reference_address_1: string;
  of_reference_telephone_1: string;
  of_reference_name_2: string;
  of_reference_address_2: string;
  of_reference_telephone_2: string;
  of_reference_name_3: string;
  of_reference_address_3: string;
  of_reference_telephone_3: string;
  of_government_id: string;
  of_id_no: string;
  of_issuance: string;
  profile: File;
};

export type PDSForm = {
  personal_information: PersonalInformation;
  family_background: FamilyBackground;
  educational_background: EducationBackground;
  civil_service_eligibility: CivilServiceEligibility;
  work_experience: WorkExperience;
  voluntary_work: VoluntaryWork;
  learning_development: LearningDevelopment;
  other_information: OtherInformation;
  employee_id: number;
  employment_status: string;
  position: string;
  department: string;
  first_day_service: string;
};

export default PDSForm;
