import PDSForm from "../types/form";

const dummyPDS: PDSForm = {
  personal_information: {
    p_surname: "DOE",
    p_first_name: "JOHN",
    p_middle_name: "Michael",
    p_name_extension: "Jr.",
    p_birth_date: "1990-01-01",
    p_birth_place: "New York, USA",
    p_sex_male: "p_sex_male",
    p_sex_female: "",
    p_civil_single: "p_civil_single",
    p_civil_widowed: "",
    p_civil_married: "",
    p_civil_separated: "",
    p_civil_other: "",
    p_weight: "70kg",
    p_height: "5ft 9in",
    p_blood_type: "O+",
    p_gsis_no: "1234567890",
    p_pagibig_no: "0987654321",
    p_philhealth_no: "1122334455",
    p_sss_no: "5566778899",
    p_tin_no: "6677889900",
    p_agency_no: "A12345",
    p_citizen_filipino: "p_citizen_flipino",
    p_citizen_dual: "",
    p_citizen_by_birth: "p_citizen_by_birth",
    p_citizen_by_naturalization: "",
    p_ra_house: "123",
    p_ra_street: "Main St",
    p_ra_subdivision: "Downtown",
    p_ra_barangay: "Central",
    p_ra_city: "New York",
    p_ra_province: "NY",
    p_ra_zip: "10001",
    p_pa_house: "123",
    p_pa_street: "Main St",
    p_pa_subdivision: "Downtown",
    p_pa_barangay: "Central",
    p_pa_city: "New York",
    p_pa_province: "NY",
    p_pa_zip: "10001",
    p_telephone: "123-456-7890",
    p_mobile: "987-654-3210",
    p_email: "johndoe@example.com",
  },
  family_background: {
    fb_spouse_surname: "Doe",
    fb_spouse_first_name: "Jane",
    fb_spouse_middle_name: "Anne",
    fb_spouse_name_extension: "Sr.",
    fb_spouse_occupation: "Engineer",
    fb_spouse_employer: "TechCorp",
    fb_spouse_business: "Software Development",
    fb_spouse_telephone: "123-456-7890",
    fb_father_surname: "Doe",
    fb_father_first_name: "James",
    fb_father_middle_name: "Henry",
    fb_father_name_extension: "Sr.",
    fb_mother_maiden_name: "Smith",
    fb_mother_surname: "Doe",
    fb_mother_first_name: "Linda",
    fb_mother_middle_name: "Grace",
    fb_children_name_1: "Alice Doe",
    fb_children_birth_date_1: "2015-06-01",
    fb_children_name_2: "Bob Doe",
    fb_children_birth_date_2: "2018-09-12",
    fb_children_name_3: "Charlie Doe",
    fb_children_birth_date_3: "2020-03-15",
    fb_children_name_4: "Daisy Doe",
    fb_children_birth_date_4: "2022-07-20",
    fb_children_name_5: "Eve Doe",
    fb_children_birth_date_5: "2024-01-01",
    fb_children_name_6: "",
    fb_children_birth_date_6: "",
    fb_children_name_7: "",
    fb_children_birth_date_7: "",
    fb_children_name_8: "",
    fb_children_birth_date_8: "",
    fb_children_name_9: "",
    fb_children_birth_date_9: "",
    fb_children_name_10: "",
    fb_children_birth_date_10: "",
    fb_children_name_11: "",
    fb_children_birth_date_11: "",
    fb_children_name_12: "",
    fb_children_birth_date_12: "",
  },
  educational_background: {
    eb_e_school_name: "New York Elementary School",
    eb_e_basic_education: "Elementary",
    eb_e_period_from: "1996",
    eb_e_period_to: "2002",
    eb_e_units_earned: "",
    eb_e_year_graduated: "2002",
    eb_e_honor_received: "Honor Student",
    eb_s_school_name: "New York High School",
    eb_s_basic_education: "High School",
    eb_s_period_from: "2002",
    eb_s_period_to: "2006",
    eb_s_units_earned: "",
    eb_s_year_graduated: "2006",
    eb_s_honor_received: "With Honors",
    eb_v_school_name: "New York Vocational School",
    eb_v_basic_education: "Vocational",
    eb_v_period_from: "2006",
    eb_v_period_to: "2008",
    eb_v_units_earned: "30",
    eb_v_year_graduated: "2008",
    eb_v_honor_received: "Top of the Class",
    eb_c_school_name: "New York College",
    eb_c_basic_education: "College",
    eb_c_period_from: "2008",
    eb_c_period_to: "2012",
    eb_c_units_earned: "120",
    eb_c_year_graduated: "2012",
    eb_c_honor_received: "Cum Laude",
    eb_gs_school_name: "New York Graduate School",
    eb_gs_basic_education: "Graduate School",
    eb_gs_period_from: "2012",
    eb_gs_period_to: "2014",
    eb_gs_units_earned: "60",
    eb_gs_year_graduated: "2014",
    eb_gs_honor_received: "Dean's List",
    eb_date: "2024-01-01",
  },
  civil_service_eligibility: [
    {
      cse: "Civil Service Exam",
      cse_rating: "85%",
      cse_exam_date: "2010-05-10",
      cse_exam_place: "New York",
      cse_license_number: "CSE123456",
      cse_validity_date: "2025-05-10",
    },
  ],
  work_experience: [
    {
      w_from: "2012",
      w_to: "2020",
      w_position: "Software Engineer",
      w_department: "IT",
      w_salary: 80000,
      w_pay_grade: "A1",
      w_soa: "Permanent",
      w_gov_service: "",
    },
    {
      w_from: "2020",
      w_to: "2024",
      w_position: "Senior Software Engineer",
      w_department: "IT",
      w_salary: 100000,
      w_pay_grade: "A2",
      w_soa: "Permanent",
      w_gov_service: "",
    },
  ],
  voluntary_work: [
    {
      vw_organization: "Red Cross",
      vw_from: "2015",
      vw_to: "2018",
      vw_hours: 200,
      vw_position: "Volunteer",
    },
    {
      vw_organization: "Habitat for Humanity",
      vw_from: "2018",
      vw_to: "2020",
      vw_hours: 150,
      vw_position: "Volunteer",
    },
  ],
  learning_development: [
    {
      ld_learning: "Advanced Python Training",
      ld_from: "2021-06-01",
      ld_to: "2021-06-30",
      ld_hours: "40",
      ld_type: "Technical",
      ld_conducted: "Online Academy",
    },
    {
      ld_learning: "Leadership Training",
      ld_from: "2022-01-01",
      ld_to: "2022-01-15",
      ld_hours: "20",
      ld_type: "Management",
      ld_conducted: "Leadership Institute",
    },
  ],
  other_information: {
    w_date: "2024-01-01",
    skills: [
      {
        of_skill: "Programming",
        of_recognition: "Best Developer Award",
        of_membership: "IEEE Member",
      },
      {
        of_skill: "Project Management",
        of_recognition: "Project Manager of the Year",
        of_membership: "PMP Certified",
      },
    ],
    of_date: "2024-01-01",
    of_third_degree_yes: "",
    of_third_degree_no: "of_third_degree_no",
    of_fourth_degree_yes: "",
    of_fourth_degree_no: "of_fourth_degree_no",
    of_affinity_details: "N/A",
    of_guilty_yes: "",
    of_guilty_no: "of_guilty_no",
    of_guilty_details: "N/A",
    of_criminal_yes: "",
    of_criminal_no: "of_criminal_no",
    of_criminal_date_filled: "N/A",
    of_criminal_status: "N/A",
    of_convicted_yes: "",
    of_convicted_no: "of_convicted_no",
    of_convicted_details: "N/A",
    of_resignation_yes: "",
    of_resignation_no: "of_resignation_no",
    of_resignation_details: "N/A",
    of_candidate_yes: "",
    of_candidate_no: "of_candidate_no",
    of_candidate_details: "N/A",
    of_government_yes: "",
    of_government_no: "of_government_no",
    of_government_details: "N/A",
    of_immigrant_yes: "",
    of_immigrant_no: "of_immigrant_no",
    of_immigrant_details: "N/A",
    of_indigenous_yes: "",
    of_indigenous_no: "of_indigenous_no",
    of_indigenous_details: "N/A",
    of_disability_yes: "",
    of_disability_no: "of_disability_no",
    of_disability_details: "N/A",
    of_solo_parent_yes: "",
    of_solo_parent_no: "of_solo_parent_no",
    of_solo_parent_details: "N/A",
    of_reference_name_1: "Jane Smith",
    of_reference_address_1: "123 Elm St, NY",
    of_reference_telephone_1: "987-654-3210",
    of_reference_name_2: "John Brown",
    of_reference_address_2: "456 Oak St, NY",
    of_reference_telephone_2: "123-456-7890",
    of_reference_name_3: "Emily White",
    of_reference_address_3: "789 Pine St, NY",
    of_reference_telephone_3: "321-654-0987",
    of_government_id: "Passport",
    of_id_no: "A123456789",
    of_issuance: "2023-05-10",
    of_profile: {
      fileName: "",
      fileType: "",
      fileContent: "",
    },
  },
  position: "PERMANENT",
  department: "OFFICE OF THE GENERAL",
  employee_id: "",
  employment_status: "",
  first_day_service: "",
};

export default dummyPDS;
