# Generated by Django 5.1.5 on 2025-02-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_table_alter_file_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('Certificate of CSC Eligibility', 'csc'), ('Diplomas, Commendations and Awards', 'dca'), ('Marriage Contract', 'mco'), ('Marriage Certificate', 'mce'), ('NBI Clearance', 'nbi'), ('Personal Data Sheet', 'pds'), ('Birth Certificate', 'bc'), ('Resume, Biodata', 'rb'), ('Birth Certificate of Child/ren', 'bcc'), ('Transcript of Records', 'tor'), ('Form 137', 'form137'), ('Form 138-A', 'form138'), ("Driver's License (Photocopy)", 'dl'), ('PRC License (Photocopy)', 'prc'), ('Training Certificate', 'tc'), ('Appointments', 'a'), ('Assumption of Duty', 'aod'), ('Certificate of Leave Balances', 'colb'), ('Contract of Services', 'cos'), ('Copies of Disciplinary Actions', 'cda'), ('Notice of Salary Adjustment/Step Increment', 'nosa'), ('Oath of Office', 'oo'), ('Position Description Forms', 'pdf'), ('SSS', 'sss'), ('Pag-Ibig', 'pi'), ('Philhealth', 'p'), ('TIN No.', 'tin'), ('None', 'na')], default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
